

CREATE TABLE [dbo].[tblEmails](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](4000) NULL,
	[EmailType] [int] NULL,
 CONSTRAINT [PK_tblEmails] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


