'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8937
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SmartScale.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property A4P_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A4P Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Abstract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abstract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property add2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_left_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_right_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_up_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Arrows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property background1_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property beep_05() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_05", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property BtnDelete_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnDelete.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property BtnNew_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnNew.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnReport_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnReport.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property BtnSave_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnSave.Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property button_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property decrypted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("decrypted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Done() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Done", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property EnterBean() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("EnterBean", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property EnterMeal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("EnterMeal", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property GetUp() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("GetUp", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kdict() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kdict", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property klpq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klpq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property media_play_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_play_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property media_play2_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_play2_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property media_step_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_step_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property media_step_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_step_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property package_system() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_system", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property PicPrint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PicPrint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property PicSearch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PicSearch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property SearchPrepare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SearchPrepare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property text_align_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TodayTrans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TodayTrans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TOLEDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TOLEDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TransID() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransID", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property truck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property yen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
